services:
  neo4j:
    image: neo4j:5.15-community
    container_name: neo4j-dev
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      # 認証設定
      NEO4J_AUTH: neo4j/password
      
      # パフォーマンス設定
      NEO4J_dbms_memory_heap_initial__size: 512M
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_dbms_memory_pagecache_size: 256M
      
      # セキュリティ設定
      NEO4J_dbms_security_procedures_unrestricted: gds.*,apoc.*
      NEO4J_dbms_security_procedures_allowlist: gds.*,apoc.*
      
      # ログ設定（修正）
      NEO4J_dbms_logs_query_enabled: INFO
      NEO4J_dbms_logs_query_threshold: 0
      
      # その他の設定
      NEO4J_dbms_default__listen__address: 0.0.0.0
      NEO4J_dbms_default__advertised__address: localhost
      
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p password 'RETURN 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local 